[package]
name = "vikos"
version = "0.1.6"
authors = ["Markus Klein <markus-klein@live.de>"]
description = "A machine learning library for supervised training of parametrized models"
license = "MIT"
repository = "https://github.com/blue-yonder/vikos"
documentation = "https://docs.rs/vikos/"
readme = "README.md"

[dependencies]
num = "0.1.35"
clippy = {version= "0.0.90", optional = true }

[features]
default = []
dev = [ "clippy" ]


