[package]
name = "vikos"
version = "0.1.1"
authors = ["Markus Klein <markus-klein@live.de>"]
description = "A machine learning library for supervised training of parametrized models"
license = "MIT"
repository = "https://github.com/blue-yonder/vikos"
documentation = "https://docs.rs/vikos/"

[dependencies]
num = "0.1"