[package]
name = "vikos"
version = "0.1.7"
authors = ["Holger Peters <holger.peters@blue-yonder.com>", "Markus Klein <markus.klein@blue-yonder.com>"]
description = "A machine learning library for supervised training of parametrized models"
license = "MIT"
repository = "https://github.com/blue-yonder/vikos"
documentation = "https://docs.rs/vikos/"
readme = "README.md"
keywords = ["machine","learning","machine-learning"]

[dependencies]
num = "0.1.35"
rustc-serialize = "0.3.19"
clippy = {version= "0.0.90", optional = true }

[dev-dependencies]
csv = "0.14.7"

[features]
default = []
dev = [ "clippy" ]
